{"urls":[
{"url":"http://www.饭太硬.net/tv","name":"✳️饭硬✳️"},
{"url":"http://肥猫.net","name":"✳️肥猫✳️"},
{"url":"http://tvbox.王二小放牛娃.top","name":"✳️放牛✳️"},
{"url":"http://我不是.摸鱼儿.top","name":"✳️摸鱼✳️"},
{"url":"https://cnb.cool/fish2018/xs/-/git/raw/main/api.json","name":"✳️潇洒✳️"},
{"url":"https://cnb.cool/fish2018/pg/-/git/raw/main/jsm.json","name":"✳️熊猫✳️"},
{"url":"https://cnb.cool/fish2018/zx/-/git/raw/master/FongMi.json","name":"✳️真心✳️"},
{"url":"http://mytv6688.xyz/aowu/config.webp","name":"✳️嗷呜✳️"},
{"url":"https://盒子迷.top/禁止贩卖","name":"✳️盒迷✳️"},
{"url":"http://宝盒接口.top","name":"✳️宝盒✳️"},
{"url":"https://yydf.540734621.xyz/yydf/yydf/yydf.json","name":"✳️业余✳️"},
{"url":"https://ghfast.top/https://raw.githubusercontent.com/maoystv/6/main/001.json","name":"✳️分享✳️"},
{"url":"https://ghfast.top/https://raw.githubusercontent.com/chitue/dongliTV/main/api.json","name":"✳️东篱✳️"},
{"url":"https://ghfast.top/https://raw.githubusercontent.com/leevi0709/one/refs/heads/main/config.bin","name":"✳️多多✳️"},
{"url":"https://ghfast.top/https://raw.githubusercontent.com/4TVBox/TVBox/refs/heads/main/config.json","name":"✳️沐辰✳️"},
{"url":"https://ghfast.top/https://raw.githubusercontent.com/yoursmile66/TVBox/main/XC.json","name":"✳️南风✳️"},
{"url":"https://ghfast.top/https://raw.githubusercontent.com/ggrrttyyiii/CatVodSpider/main/json/demo.json","name":"✳️小米✳️"}
]}
